=begin
#Maestro API

#Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise

OpenAPI spec version: 1.0.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_Maestro
  class DSWorkflowComparisonOperatorTypes
    
    CONTAINS = 'Contains'.freeze
    NOT_CONTAINS = 'NotContains'.freeze
    EQUAL = 'Equal'.freeze
    NOT_EQUAL = 'NotEqual'.freeze
    GREATER_THAN = 'GreaterThan'.freeze
    GREATER_THAN_OR_EQUAL = 'GreaterThanOrEqual'.freeze
    LESS_THAN = 'LessThan'.freeze
    LESS_THAN_OR_EQUAL = 'LessThanOrEqual'.freeze
    STARTS_WITH = 'StartsWith'.freeze
    NOT_STARTS_WITH = 'NotStartsWith'.freeze
    ENDS_WITH = 'EndsWith'.freeze
    NOT_ENDS_WITH = 'NotEndsWith'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = DSWorkflowComparisonOperatorTypes.constants.select { |c| DSWorkflowComparisonOperatorTypes::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #DSWorkflowComparisonOperatorTypes" if constantValues.empty?
      value
    end
  end
end
