=begin
#Maestro API

#Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise

OpenAPI spec version: 1.0.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_Maestro
  class ErrorCodes
    
    N10001 = 'ERR_10001'.freeze
    N10002 = 'ERR_10002'.freeze
    N10003 = 'ERR_10003'.freeze
    N10004 = 'ERR_10004'.freeze
    N10005 = 'ERR_10005'.freeze
    N10006 = 'ERR_10006'.freeze
    N10007 = 'ERR_10007'.freeze
    N10008 = 'ERR_10008'.freeze
    N10009 = 'ERR_10009'.freeze
    N10101 = 'ERR_10101'.freeze
    N10201 = 'ERR_10201'.freeze
    N10202 = 'ERR_10202'.freeze
    N10301 = 'ERR_10301'.freeze
    N10302 = 'ERR_10302'.freeze
    N10801 = 'ERR_10801'.freeze
    N10802 = 'ERR_10802'.freeze
    N10999 = 'ERR_10999'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ErrorCodes.constants.select { |c| ErrorCodes::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ErrorCodes" if constantValues.empty?
      value
    end
  end
end
