=begin
#Maestro API

#Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise

OpenAPI spec version: 1.0.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_Maestro
  class EventTypes
    
    ENVELOPE_SENT = 'envelope-sent'.freeze
    ENVELOPE_DELIVERED = 'envelope-delivered'.freeze
    ENVELOPE_COMPLETED = 'envelope-completed'.freeze
    ENVELOPE_DECLINED = 'envelope-declined'.freeze
    ENVELOPE_VOIDED = 'envelope-voided'.freeze
    ENVELOPE_CREATED = 'envelope-created'.freeze
    ENVELOPE_RESENT = 'envelope-resent'.freeze
    ENVELOPE_CORRECTED = 'envelope-corrected'.freeze
    ENVELOPE_PURGE = 'envelope-purge'.freeze
    ENVELOPE_DELETED = 'envelope-deleted'.freeze
    ENVELOPE_DISCARD = 'envelope-discard'.freeze
    DELIVERY_FAILED = 'Delivery Failed'.freeze
    AUTHENTICATION_FAILED = 'Authentication Failed'.freeze
    SENT = 'Sent'.freeze
    DELIVERED = 'Delivered'.freeze
    SIGNED = 'Signed'.freeze
    COMPLETED = 'Completed'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = EventTypes.constants.select { |c| EventTypes::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #EventTypes" if constantValues.empty?
      value
    end
  end
end
