=begin
#Maestro API

#Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise

OpenAPI spec version: 1.0.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_Maestro
  class ReplicationStatus
    
    DEPLOY_REPLICATION_IN_PROGRESS = 'Deploy Replication In Progress'.freeze
    DEPLOY_REPLICATED = 'Deploy Replicated'.freeze
    DEPLOY_REPLICATION_FAILED = 'Deploy Replication Failed'.freeze
    NOT_REPLICATED = 'Not Replicated'.freeze
    DELETE_REPLICATION_IN_PROGRESS = 'Delete Replication in Progress'.freeze
    DELETE_REPLICATED = 'Delete Replicated'.freeze
    DELETE_REPLICATION_FAILED = 'Delete Replication Failed'.freeze
    UNPUBLISH_REPLICATION_IN_PROGRESS = 'Unpublish replication in Progress'.freeze
    UNPUBLISH_REPLICATED = 'Unpublish Replicated'.freeze
    UNPUBLISH_REPLICATION_FAILED = 'Unpublish Replication Failed'.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = ReplicationStatus.constants.select { |c| ReplicationStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #ReplicationStatus" if constantValues.empty?
      value
    end
  end
end
